In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,2985,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [3]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [4]:
df.dropna(inplace=True)

In [5]:
X = df.drop(["customerID", "Churn"], axis=1)
Y = df["Churn"]

In [6]:
X = pd.get_dummies(X, drop_first=True)

In [7]:
X.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='str')

In [9]:
pd.get_dummies(df, columns=["gender", "Partner"])

,customerID,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes
0,7590-VHVEG,0,No,1,No,No phone service,DSL,No,Yes,No,...,Month-to-month,Yes,Electronic check,29.85,2985.00,No,True,False,False,True
1,5575-GNVDE,0,No,34,Yes,No,DSL,Yes,No,Yes,...,One year,No,Mailed check,56.95,1889.50,No,False,True,True,False
2,3668-QPYBK,0,No,2,Yes,No,DSL,Yes,Yes,No,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,False,True,True,False
3,7795-CFOCW,0,No,45,No,No phone service,DSL,Yes,No,Yes,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,False,True,True,False
4,9237-HQITU,0,No,2,Yes,No,Fiber optic,No,No,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,Yes,24,Yes,Yes,DSL,Yes,No,Yes,...,One year,Yes,Mailed check,84.80,1990.50,No,False,True,False,True
7039,2234-XADUH,0,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,...,One year,Yes,Credit card (automatic),103.20,7362.90,No,True,False,False,True
7040,4801-JZAZL,0,Yes,11,No,No phone service,DSL,Yes,No,No,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,True,False,False,True
7041,8361-LTMKD,1,No,4,Yes,Yes,Fiber optic,No,No,No,...,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,False,True,False,True
7042,3186-AJIEK,0,No,66,Yes,No,Fiber optic,Yes,No,Yes,...,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,False,True,True,False

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
 X,Y, test_size=0.25
)

In [33]:
print(X_train.head())   
print(X_train.dtypes)

      SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender_Male  \
5263              1      55           44.85       2479.05         True
6981              0       8           65.45        554.45        False
565               0      71           70.85       4973.40         True
3209              0       1           93.85         93.85        False
5192              0      60           19.95       1189.90         True

      Partner_Yes  Dependents_Yes  PhoneService_Yes  \
5263        False           False             False
6981        False           False              True
565          True            True              True
3209        False           False              True
5192        False            True              True

      MultipleLines_No phone service  MultipleLines_Yes  ...  \
5263                            True              False  ...
6981                           False              False  ...
565                            False              False  ...
3209                           False               True  ...
5192                           False              False  ...

      StreamingTV_No internet service  StreamingTV_Yes  \
5263                            False             True
6981                            False             True
565                             False            False
3209                            False             True
5192                             True            False

      StreamingMovies_No internet service  StreamingMovies_Yes  \
5263                                False                False
6981                                False                False
565                                 False                 True
3209                                False                 True
5192                                 True                False

      Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
5263              False              False                  True
6981              False              False                  True
565               False               True                  True
3209              False              False                  True
5192              False               True                 False

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
5263                                  False                            True
6981                                  False                            True
565                                    True                           False
3209                                  False                            True
5192                                  False                           False

      PaymentMethod_Mailed check
5263                       False
6981                       False
565                        False
3209                       False
5192                        True

[5 rows x 30 columns]
SeniorCitizen                              int64
tenure                                     int64
MonthlyCharges                           float64
TotalCharges                             float64
gender_Male                                 bool
Partner_Yes                                 bool
Dependents_Yes                              bool
PhoneService_Yes                            bool
MultipleLines_No phone service              bool
MultipleLines_Yes                           bool
InternetService_Fiber optic                 bool
InternetService_No                          bool
OnlineSecurity_No internet service          bool
OnlineSecurity_Yes                          bool
OnlineBackup_No internet service            bool
OnlineBackup_Yes                            bool
DeviceProtection_No internet service        bool
DeviceProtection_Yes                        bool
TechSupport_No internet service             bool
TechSupport_Yes                             bool
StreamingTV_No internet service             bool
StreamingTV_Yes                             bool
StreamingMovies_No internet service         bool
StreamingMovies_Yes                         bool
Contract_One year                           bool
Contract_Two year                           bool
PaperlessBilling_Yes                        bool
PaymentMethod_Credit card (automatic)       bool
PaymentMethod_Electronic check              bool
PaymentMethod_Mailed check                  bool
dtype: object

In [34]:
len(X_train),len(X_test)

(5274, 1758)

In [35]:
print(X.columns)

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='str')

In [36]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [37]:
print(df.isnull().sum())
print(X.isnull().sum()) 
print(X.isnull().sum().sum())

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64
SeniorCitizen                            0
tenure                                   0
MonthlyCharges                           0
TotalCharges                             0
gender_Male                              0
Partner_Yes                              0
Dependents_Yes                           0
PhoneService_Yes                         0
MultipleLines_No phone service           0
MultipleLines_Yes                        0
InternetService_Fiber optic              0
InternetService_No                       0
OnlineSecurity_No internet service       0
OnlineSecurity_Yes                       0
OnlineBackup_No internet service         0
OnlineBackup_Yes                         0
DeviceProtection_No internet service     0
DeviceProtection_Yes                     0
TechSupport_No internet service          0
TechSupport_Yes                          0
StreamingTV_No internet service          0
StreamingTV_Yes                          0
StreamingMovies_No internet service      0
StreamingMovies_Yes                      0
Contract_One year                        0
Contract_Two year                        0
PaperlessBilling_Yes                     0
PaymentMethod_Credit card (automatic)    0
PaymentMethod_Electronic check           0
PaymentMethod_Mailed check               0
dtype: int64
0

In [38]:
from sklearn.neighbors import KNeighborsClassifier
model= KNeighborsClassifier()
model.fit(X_train,Y_train)
Y_pred= model.predict(X_test)

In [39]:
Y_pred

array(['Yes', 'No', 'No', ..., 'Yes', 'Yes', 'No'],
      shape=(1758,), dtype=object)

In [41]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_pred)*100)

76.3367463026166

In [46]:
from sklearn.tree import DecisionTreeClassifier
model_dt= DecisionTreeClassifier()
model_dt.fit(X_train,Y_train)
Y_pred_dt= model_dt.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_pred)*100)

79.46530147895335

In [48]:
from sklearn.ensemble import RandomForestClassifier
model_rm= RandomForestClassifier()
model_rm.fit(X_train,Y_train)
Y_pred_rm= model_rm.predict(X_test)

In [49]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_pred)*100)

79.46530147895335

In [55]:
from sklearn.metrics import classification_report
knn_report= classification_report(Y_test,Y_pred)
dt_report= classification_report(Y_test,Y_pred_dt)
rf_report= classification_report(Y_test,Y_pred_rm)

In [57]:
print('knn report',knn_report)

knn report               precision    recall  f1-score   support

          No       0.84      0.90      0.87      1299
         Yes       0.63      0.51      0.56       459

    accuracy                           0.79      1758
   macro avg       0.74      0.70      0.71      1758
weighted avg       0.78      0.79      0.79      1758

In [58]:
print('dt report', dt_report)

dt report               precision    recall  f1-score   support

          No       0.83      0.80      0.82      1299
         Yes       0.49      0.53      0.51       459

    accuracy                           0.73      1758
   macro avg       0.66      0.67      0.66      1758
weighted avg       0.74      0.73      0.74      1758

In [60]:
print('rf report' ,rf_report)

rf report               precision    recall  f1-score   support

          No       0.84      0.90      0.87      1299
         Yes       0.64      0.50      0.56       459

    accuracy                           0.80      1758
   macro avg       0.74      0.70      0.71      1758
weighted avg       0.78      0.80      0.79      1758

In [61]:
from sklearn.naive_bayes import BernoulliNB
model_nb= BernoulliNB()
model_nb.fit(X_train,Y_train)
Y_pred_nb= model_nb.predict(X_test)

In [63]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_pred_nb)*100)

73.15130830489193

In [67]:
from sklearn.svm import SVC
model_svm= SVC()
model_svm.fit(X_train,Y_train)
Y_pred_svm= model_svm.predict(X_test)

In [68]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_pred_svm)*100)

80.71672354948805

In [70]:
from sklearn.metrics import classification_report
nb_report= classification_report(Y_test,Y_pred_nb)
svm_report = classification_report(Y_test,Y_pred_svm)

In [71]:
print('nb report', nb_report)

nb report               precision    recall  f1-score   support

          No       0.91      0.70      0.79      1299
         Yes       0.49      0.81      0.61       459

    accuracy                           0.73      1758
   macro avg       0.70      0.76      0.70      1758
weighted avg       0.80      0.73      0.75      1758

In [72]:
print('svm report', svm_report )

svm report               precision    recall  f1-score   support

          No       0.84      0.91      0.88      1299
         Yes       0.68      0.50      0.58       459

    accuracy                           0.81      1758
   macro avg       0.76      0.71      0.73      1758
weighted avg       0.80      0.81      0.80      1758